### ISSUE TITLE
最好能通过Resample方式从tic文件中得到1MIN/5MIN/1Day周期的K线数据???

### ISSUE THREAD

**Issue by zfsamzfsam** [datochan/ParseTicFile#1]
如题
这样可以只下载一个文件得到多种周期的数据!

**Comment by datochan** [comment]
这个项目不是单独的项目，只是为了解决 [pytdx项目中tic数据解析](https://github.com/rainx/pytdx/issues/149)中tic文件格式的问题。所以不会做您提的这个工作。

另外，一般的项目中 数据获取 与 数据转换是要分开做的。这样项目才便于扩展。
