### ISSUE TITLE
这里面的笔数信息没有解析出来，就是TickTradeDetail这里面的count信息。

### ISSUE THREAD

**Issue by hellobiek** [datochan/ParseTicFile#3]

**Comment by hellobiek** [comment]
如果没有这个count的话，请删除掉。

**Comment by hellobiek** [comment]
另外，数据还是稍微有一些不一致。不知道是不是哪有有bug。

**Comment by datochan** [comment]
说明一下哪只股票，哪一天的数据吧？
我也只是逆了通达信的解析打开，照抄的。
毕竟我这边用不到，所以没做太多测试，bug应该会有的，你说明一下，我对照着看看。

**Comment by hellobiek** [comment]
首先，通过bytes反解析结构真的很牛B，大赞。

我已经把你的go翻译成了python，发现的问题如下，
1、601318（中国平安） 2017-07-03的数据就和通过接口获取的数据不一致。
2、所有的数据都没有处理TickTradeDetail的count结构，所有的count，除了第一行，其他都为0。
3、代码review上，我觉得使用goto其实不太好。
4、通过你的代码，解析的数据里没有amount（成交额）信息。

基于以上原因，我已经改成从接口获取了。

**Comment by datochan** [comment]
恩，我对比了一下数据，也看了一下之前的笔记，确定如下信息:

1. 没有对count结构的解析，只是通过hash表对价格和时间，交易量的解析(第一行是明文给出，没有经过计算所以有), 也没有成交额信息。
1. 由于我是直接逆的汇编代码，所以代码确实比较挫，不过看懂意思可以将代码改成循环或者递归的，由于我这边用不到这部分功能，所以确实没有用心。
1. 我对比了下数据，通过通达信协议获取的数据，确实与tic解析的对不上，还是建议你用接口获取数据吧。

**Comment by hellobiek** [comment]
接口太慢了，所以才实现了你的功能，可惜了！！

只好使用接口了。

陈俊州 <notifications@github.com> 于2018年7月17日周二 下午8:50写道：

**Comment by hellobiek** [comment]
各种平台赚了一圈，各种缺数据，各种不靠谱。真是不行。还是你的这个方法牛B。

**Comment by hellobiek** [comment]
hello，@datochan 方便指导如何反汇编代码吗？

例如如何进行反汇编解析通达信。

我想在你的基础之上好好改改，希望能进一步的改进。

**Comment by datochan** [comment]
@hellobiek 额，我最开始弄数据的时候也是从网页或者第三方接口中爬数据的，后来也是发现各种数据不准。我身边一些老股民用通达信的比较多，所以就想解析通达信的协议，拿通达信的数据。

但是通达信与同花顺，东方财富这些的数据仍然有差别的，所以数据上我估计没有哪个人敢说自己的数据没有差错(这个主要可能是各家的衡量指标不统一导致的一些误差)，没有必要太过纠结这个问题。

至于反汇编代码，我是学校有教C语言，网上查一下X86的汇编教程，了解一下寄存器规则，函数调用规范什么的，C++的内存结构大概了解一下，知道怎么定位this指针，虚函数表什么的免得跟丢了。最后就找个汇编指令的手册，再了解一下汇编级的调试器。剩下的就是自己一点点的调试分析读代码了。

对了，有个反汇编的工具IDA，它有个F5插件，可以将反汇编代码翻译成C的伪指令，再泛读代码时，可以提高效率，对比着汇编代码去阅读应该会降低不少难度。

差不多就这些，祝你成功~
