### ISSUE TITLE
在验证正确性的时候发现一个bug

### ISSUE THREAD

**Issue by hellobiek** [datochan/ParseTicFile#6]
日期20150701，股票002437的解析结果不对。

会出现下面的结果：

3585     14:50,  42949674.25,    57, 0,  0
3586     14:50,  42949674.25,    253,    0,  1
3587     14:50,  42949674.25,    48, 0,  1
3588     14:50,  42949674.25,    221,    0,  0
3589     14:50,  42949674.25,    23, 0,  1
3590     14:50,  42949674.25,    102,    0,  1
3591     14:50,  42949674.25,    202,    0,  1
3592     14:50,  42949674.25,    151,    0,  1
3593     14:50,  42949674.25,    150,    0,  0
3594     14:50,  42949674.25,    247,    0,  0
3595     14:50,  42949674.25,    138,    0,  0

**Comment by datochan** [comment]
呃呃呃，这个代码是在pytdx项目中，有人让我分析一下 tick 数据，我为了验证分析结果写的一个样例小程序。

由于这个功能我用不到，也没想过好好维护，目前也没有多少经理看这些bug。您可以根据代码去分析一下这个数据结构，修复一下Bug。
