### ISSUE TITLE
tdx 分时数据格式

### ISSUE THREAD

**Issue by catsalt** [datochan/ParseTicFile#9]
你好, 二代是Tic, 三代是HTC, 怎么处理?

**Comment by datochan** [comment]
我没有分析过三代的数据格式。
分析第二代的格式也只是因为有个帖子中问，一时兴起分析的。

由于我实际上用不到这部分数据，所以当时分析时也只是初略的看了一下，并没有仔细的核实数据的准确性。

而且以后如果没有必要，应该也不会继续分析了。

感谢您的关注！如果可以，希望你能分享出你对三代htc的分析成果，相信可以帮助到不少人~

**Comment by catsalt** [comment]
我在网上都没有找到二代tic 的数据格式, 你在哪里获取到的? 有渠道吗? 如果有的话, 请帮忙提供一下, 二代,三代的数据格式, 我来写转换工具.  谢谢.

**Comment by datochan** [comment]
额，我是自己连蒙带猜的分析出来的。没有什么渠道~
